### ISSUE TITLE
Specifying CES endpoints direcly?

### ISSUE THREAD

**Issue by joakim-tjernlund** [ufven/cepces#1]
Our Win2008 CA does not have CEP configured. Would it be possible to have config entries
for specifying CES directly?

**Comment by ufven** [comment]
Unfortunately, not at the moment. However, I'm working on a new release, and I'll try to include this request there.

**Comment by joakim-tjernlund** [comment]
OK, looking forward to next release then :)

Will it be possible to create other types of certs,  like User ?

**Comment by joakim-tjernlund** [comment]
BTW, certmonger installs xxx-submit under /usr/libexec/certmonger, maybe move cepces-submit there too?

**Comment by joakim-tjernlund** [comment]
How is the release coming along?

**Comment by ufven** [comment]
Sorry for the late response.

> Will it be possible to create other types of certs, like User ?

Since certmonger is a hard dependency right now, and that Kerberos (using a keytab) is the only supported authentication mechanism, whatever certificate template the identity supports will be enrollable. For a domain connected computer, this usually means the Computer or Workstation template (unless you have a user keytab).

> BTW, certmonger installs xxx-submit under /usr/libexec/certmonger, maybe move cepces-submit there too?

I just realized I never published 0.3.0 here, only internally. Those sources can be found here: https://copr.fedorainfracloud.org/coprs/ufven/cepces/

> How is the release coming along?

I've been swamped with work for the past few weeks, but started working on it this week. If everything goes as planned, it should be done in a couple of weeks. I'm rewriting parts of the (very crude) SOAP handling which should enable for username/password (and also certificate) authentication, instead of only Kerberos. With this change, I hope to build a small CLI that should enable you to issue user certificates as well. This also makes it possible to run it without certmonger as a dependency (if desired.)

Out of curiosity, what distribution are you running? I'm currently only packaging EL and Ubuntu.

**Comment by ufven** [comment]
> BTW, certmonger installs xxx-submit under /usr/libexec/certmonger, maybe move cepces-submit there too?

This was fixed in the 0.3.0 release, it made a lot of the SELinux specifics disappear.

**Comment by joakim-tjernlund** [comment]
Hi :)
I had a look at https://copr.fedorainfracloud.org/coprs/ufven/cepces/ but I don't see sources there?
Would you mind pushing your latest code to github?

BTW, I am on Gentoo

**Comment by joakim-tjernlund** [comment]
ping?

**Comment by ufven** [comment]
I'll have it published during this weekend. I found a bug during the renewal process, but I should be able to release the new version before that hits you. Stay tuned :-)

**Comment by joakim-tjernlund** [comment]
nice :) did you get support for configuring CES servers directly too?

**Comment by ufven** [comment]
Working on it, slated for the 0.4 release along with the standalone CLI. This will make it possible to use it without certmonger as well.

I couldn't find certmonger in portage, are you using some overlay?

**Comment by joakim-tjernlund** [comment]
I found an certmonger ebuild somewhere I cleaned up a little. Once I have this working I plan
submitting it to Gentoo.

Please push your work as you go to github, then I can try it out for you

**Comment by joakim-tjernlund** [comment]
Still tuned ... :)

**Comment by ufven** [comment]
Rewriting of the SOAP/XML handling turned out to be a bit over ambitious, so I revisited the old code instead. I think I got the bypassing to work, I just need to run a few more tests. This should allow you to specify a CES endpoint directly. I expect to push this to the master branch today (or at least to devel).

Unfortunately, you still need certmonger as of now (and Kerberos). I'll try to add a simple CLI as well as the possibility to use a username and password as authentication shortly.

**Comment by joakim-tjernlund** [comment]
Just had a bit of left and see that the code is there :) Thanks!
Will start building an package and test ...
BTW, do you know of a better way than:
	sed -i -e 's|/usr/local/libexec/|/usr/libexec/|' -e 's|/usr/local/etc/|/etc/|' "${S}"/setup.py
to get proper paths?

**Comment by joakim-tjernlund** [comment]
A quick try reveals:
 getcert list
Number of certificates and requests being tracked: 1.
Request ID 'MachineCertificate':
	status: NEED_GUIDANCE
	stuck: yes
....

I guess this is because I don't get the new Enrollment type
What should endpoint be:
 https://${server}/ADPolicyProvider_CEP_${auth}/service.svc/CEP
not the above I guess ?

Oh, maybe mention in README:
getcert add-ca -c cepces -e /usr/libexec/certmonger/cepces-submit

**Comment by ufven** [comment]
> I guess this is because I don't get the new Enrollment type
> What should endpoint be:
> https://${server}/ADPolicyProvider_CEP_${auth}/service.svc/CEP
> not the above I guess ?

No, that is for the CEP endpoint. They are pretty well-formed and can be deduced using the server name and authentication type. The CES endpoints are a bit more tricky. You can check through IIS on the CA server and there should be an alias. In my test environment, the alias is for the CEP endpoint is `ADPolicyProvider_CEP_Kerberos`, thus the URL would be `https://${server}/ADPolicyProvider_CEP_${auth}/service.svc/CEP`. I also have another alias named `contoso-SERVER-CA_CES_Kerberos`, which would resolve to `https://${server}/contoso-SERVER-CA_CES_${auth}/service.svc/CES`. Both `${server}` and `${auth}` refers to the other variables in the configuration file, so they are optional. You can specify the full URL if you want to.

You can also find this endpoint through ADSI Edit under `CN=Enrollment Services,CN=Public Key Services,CN=Services,CN=Configuration,DC=...`. You should have a `pKIEnrollmentService` object there which has a property called `msPKI-Enrollment-Servers`. It is prefix and suffixed by numbers (in my case `120` and `0`). Just grab the URL in between and you should be good to go. Also note that the URL has to be encoded, so any spaces should be replaced by `%20`. I'll document this in the wiki (and README).

> Oh, maybe mention in README:
> getcert add-ca -c cepces -e /usr/libexec/certmonger/cepces-submit

I thought I had added it to the wiki, but apparently not. Thanks for pointing it out! The README is also due for a rewrite, I'll get to it once I get the CLI functionality added.

Let me know how it goes :-) Check the `logging.conf` and change where the log file is written to, there may be clues in there in case something doesn't work. I haven't done extensive testing yet, so let me know if you encounter any runtime errors.

**Comment by ufven** [comment]
> Just had a bit of time left and see that the code is there :) Thanks!
> Will start building an package and test ...

Great :) You're welcome!

> BTW, do you know of a better way than:
> sed -i -e 's|/usr/local/libexec/|/usr/libexec/|' -e 's|/usr/local/etc/|/etc/|' "${S}"/setup.py
> to get proper paths?

No, not that I know of. I have a lot of macros that I can use when packaging for RPM and DEB, so I simply move the files in their right places (like `%__mv %{buildroot}/%{usr}/local/libexec/%{name}-submit %{buildroot}%{_libexecdir}/certmonger/%{name}-submit`). I haven't found a reliable way to determine such paths from within `setup.py`, therefore I put it in `/usr/local` according to the FHS.

**Comment by joakim-tjernlund** [comment]
I got problems:
 /usr/libexec/certmonger/cepces-submit --help
Traceback (most recent call last):
  File "/usr/libexec/certmonger/cepces-submit", line 26, in <module>
    from cepces.certmonger.operation import Operation
  File "/usr/lib64/python3.6/site-packages/cepces/certmonger/operation.py", line 29, in <module>
    from cepces.core import PartialChainError
  File "/usr/lib64/python3.6/site-packages/cepces/core.py", line 33, in <module>
    from cepces.wstep.service import Service as WSTEPService
  File "/usr/lib64/python3.6/site-packages/cepces/wstep/service.py", line 27, in <module>
    from cepces.wstep.types import SecurityTokenRequest
  File "/usr/lib64/python3.6/site-packages/cepces/wstep/types.py", line 27, in <module>
    from cepces.xml.converter import CertificateConverter, PKCS7Converter
ImportError: cannot import name 'PKCS7Converter'

PKCS7Converter does not seem to defined anywhere

**Comment by joakim-tjernlund** [comment]
BTW, this is useful to find the CA URL:
ldapsearch -LLL -o ldif-wrap=no -h ... -b cn=Configuration,dc=..,dc=.. '(objectClass=pKIEnrollmentService)' msPKI-Enrollment-Servers

base64 encoded though

**Comment by joakim-tjernlund** [comment]
> > Just had a bit of time left and see that the code is there :) Thanks!
> > Will start building an package and test ...
> 
> Great :) You're welcome!
> 
> > BTW, do you know of a better way than:
> > sed -i -e 's|/usr/local/libexec/|/usr/libexec/|' -e 's|/usr/local/etc/|/etc/|' "${S}"/setup.py
> > to get proper paths?
> 
> No, not that I know of. I have a lot of macros that I can use when packaging for RPM and DEB, so I simply move the files in their right places (like `%__mv %{buildroot}/%{usr}/local/libexec/%{name}-submit %{buildroot}%{_libexecdir}/certmonger/%{name}-submit`). I haven't found a reliable way to determine such paths from within `setup.py`, therefore I put it in `/usr/local` according to the FHS.

Maybe have a variable PREFIX=/usr/local that can be overriden?

**Comment by ufven** [comment]
> PKCS7Converter does not seem to defined anywhere

Hmm, that shouldn't have been merged... I'm not sure why I didn't catch that. You can uncomment that line. I'll prepare a hot fix.

**Comment by joakim-tjernlund** [comment]
What about this line then?
                     token = XMLValue('BinarySecurityToken',
                     converter=PKCS7Converter,
                     namespace=NS_WST_SECEXT)

**Comment by ufven** [comment]
Set that to StringConverter.

The idea is that one of the elements in the response contains the entire certificate chain, PKCS7 encoded. I had that in another branch, or so I thought, so I must have messed up somehow when merging. I never finished that part.

**Comment by joakim-tjernlund** [comment]
2019-06-04 13:18:49,452 __main__:ERROR:Traceback (most recent call last):
  File "/usr/libexec/certmonger/cepces-submit", line 61, in main
    config = Configuration.load()
  File "/usr/lib64/python3.6/site-packages/cepces/config.py", line 131, in load
    return Configuration.from_parser(config)
  File "/usr/lib64/python3.6/site-packages/cepces/config.py", line 169, in from_parser
    return Configuration(endpoint, endpoint_type, cas, authn.handle())
  File "/usr/lib64/python3.6/site-packages/cepces/auth.py", line 94, in handle
    raise RuntimeError('No suitable key found in keytab.')
RuntimeError: No suitable key found in keytab.

and in cepces.conf I got
 A list of principals to try when requesting a ticket.
#
# Default: <empty list>
principals=host/gentoo-jocke.infinera.com

**Comment by joakim-tjernlund** [comment]
OK, restoring:
principals=
  ${SHORTNAME}$$
  host/${SHORTNAME}
  host/${fqdn}

and 
 cas=False
to
 cas=/etc/ssl/certs/ca-certificates.crt
Worked :)
cas=False worked before (we didn't have a valid cert to begin with but we do now)

**Comment by joakim-tjernlund** [comment]
On your wiki dev-python/cement is listed as dependency but not in src

**Comment by joakim-tjernlund** [comment]
Would it be possible to have cepces generate a passwd protected *.key file ?
NetworkManager needs a passwd to accept a TLS WiFi connection.

**Comment by ufven** [comment]
> Restoring [...] principals Worked

Great :)

> On your wiki dev-python/cement is listed as dependency but not in src

Yes, this was a dependency in the 0.2 series, but I removed it with 0.3 since I used so little of its functionality. I'll update the wiki (and README) in the coming days. Thanks for pointing it out :)

> Would it be possible to have cepces generate a passwd protected *.key file ?
> NetworkManager needs a passwd to accept a TLS WiFi connection.

Not in its current state. However, you can do this with `certmonger`.

1. Generate a PIN (key): `< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c16 > /etc/pki/tls/private/machine.pin` (or however you'd like to do it)
1. Set permissions: `chmod 0600 /etc/pki/tls/private/machine.pin`
1. Request a cert: `getcert request -c cepces -T Machine -I MachineCertificate -k /etc/pki/tls/private/machine.key -p /etc/pki/tls/private/machine.pin -f /etc/pki/tls/certs/machine.crt`

This is (roughly) how I do it. Don't forget to update the paths accordingly, these are for Fedora. The contents of the `machine.pin` is the key that you can use for NetworkManager.

**Comment by joakim-tjernlund** [comment]
Thanks, I managed to create a connection but NM will not let me in. Complains about needing
passwd or keys after a little while. I guess there is something missing in the AP config(Cisco).
Windows is working with certificates I hear though.

BTW, now getcert list shows:
Number of certificates and requests being tracked: 1.
Request ID 'MachineCertificate':
	status: NEWLY_ADDED_NEED_KEYINFO_READ_PIN
	stuck: yes
so I guess there is something missing for cert renewal.

**Comment by ufven** [comment]
I've never seen `NEWLY_ADDED_NEED_KEYINFO_READ_PIN` before. Did you re-use the same key and fed certmonger with a pin? I'm not certain that it regenerates the key if it exists. Maybe you need to remove the previous key first, before requesting a new cert (or manually encrypt the key using the supplied pin).

**Comment by joakim-tjernlund** [comment]
Hi again

Now we have figured out why not wifi TLS work against APs. The cert is fine but an extar step fails:

> Active Directory Certificate Retrieval for Certificate-Based Authentication

> Cisco ISE supports certificate retrieval for user and machine authentication that uses the EAP-TLS protocol. The user or machine record on Active Directory includes a certificate attribute of the binary data type. This certificate attribute can contain one or more certificates. Cisco ISE identifies this attribute as userCertificate and does not allow you to configure any other name for this attribute. Cisco ISE retrieves this certificate and uses it to perform binary comparison.

> The certificate authentication profile determines the field where the username is taken from in order to lookup the user in Active Directory to be used for retrieving certificates, for example, Subject Alternative Name (SAN) or Common Name. After Cisco ISE retrieves the certificate, it performs a binary comparison of this certificate with the client certificate. When multiple certificates are received, Cisco ISE compares the certificates to check for one that matches. When a match is found, the user or machine authentication is passed.

This "userCertificate" is not created for Linux clients and we suspect that cepces does something different
than what Windows does. Does this make any sense to you?

**Comment by joakim-tjernlund** [comment]
Oh, forgot one thing: The created machine.crt is on readable by root and nm-applet refuses
to use an unreadable cert, maybe create .crt readable by all?

**Comment by joakim-tjernlund** [comment]
https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-XCEP/%5BMS-XCEP%5D-160714.pdf

Could this be related to Appendix A , enrollmentFlags (0x00000008):
Instructs the CA to append the issued certificate to the userCertificate attribute, on the user
object in Active Directory.

**Comment by ufven** [comment]
> Hi again
> 
> Now we have figured out why not wifi TLS work against APs. The cert is fine but an extar step fails:
> 
> > Active Directory Certificate Retrieval for Certificate-Based Authentication
> 
> > Cisco ISE supports certificate retrieval for user and machine authentication that uses the EAP-TLS protocol. The user or machine record on Active Directory includes a certificate attribute of the binary data type. This certificate attribute can contain one or more certificates. Cisco ISE identifies this attribute as userCertificate and does not allow you to configure any other name for this attribute. Cisco ISE retrieves this certificate and uses it to perform binary comparison.
> 
> > The certificate authentication profile determines the field where the username is taken from in order to lookup the user in Active Directory to be used for retrieving certificates, for example, Subject Alternative Name (SAN) or Common Name. After Cisco ISE retrieves the certificate, it performs a binary comparison of this certificate with the client certificate. When multiple certificates are received, Cisco ISE compares the certificates to check for one that matches. When a match is found, the user or machine authentication is passed.
> 
> This "userCertificate" is not created for Linux clients and we suspect that cepces does something different
> than what Windows does. Does this make any sense to you?

Nothing I've looked into. Basically, `certmonger` generates a CSR that it feeds to `cepces`. This CSR is then sent verbatim to the CA server. The result contains a PEM encoded certificate that is then fed back to `certmonger` which then stores the certificate in the file specified.

Are you using the same certificate template on both Windows and Linux? My guess is that "Publish certificate in Active Directory" is not enabled on the template.

**Comment by ufven** [comment]
> Oh, forgot one thing: The created machine.crt is on readable by root and nm-applet refuses
> to use an unreadable cert, maybe create .crt readable by all?

Unfortunately, this is a `certmonger` issue. As per above, the file handling is done through `certmonger`. They only communicate through stdin/stdout.

**Comment by ufven** [comment]
> https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-XCEP/%5BMS-XCEP%5D-160714.pdf
> 
> Could this be related to Appendix A , enrollmentFlags (0x00000008):
> Instructs the CA to append the issued certificate to the userCertificate attribute, on the user
> object in Active Directory.

This could probably be added easily as a configuration option. I'll check it out.

**Comment by joakim-tjernlund** [comment]
> > Hi again
> > Now we have figured out why not wifi TLS work against APs. The cert is fine but an extar step fails:
> > > Active Directory Certificate Retrieval for Certificate-Based Authentication
> > 
> > 
> > > Cisco ISE supports certificate retrieval for user and machine authentication that uses the EAP-TLS protocol. The user or machine record on Active Directory includes a certificate attribute of the binary data type. This certificate attribute can contain one or more certificates. Cisco ISE identifies this attribute as userCertificate and does not allow you to configure any other name for this attribute. Cisco ISE retrieves this certificate and uses it to perform binary comparison.
> > 
> > 
> > > The certificate authentication profile determines the field where the username is taken from in order to lookup the user in Active Directory to be used for retrieving certificates, for example, Subject Alternative Name (SAN) or Common Name. After Cisco ISE retrieves the certificate, it performs a binary comparison of this certificate with the client certificate. When multiple certificates are received, Cisco ISE compares the certificates to check for one that matches. When a match is found, the user or machine authentication is passed.
> > 
> > 
> > This "userCertificate" is not created for Linux clients and we suspect that cepces does something different
> > than what Windows does. Does this make any sense to you?
> 
> Nothing I've looked into. Basically, `certmonger` generates a CSR that it feeds to `cepces`. This CSR is then sent verbatim to the CA server. The result contains a PEM encoded certificate that is then fed back to `certmonger` which then stores the certificate in the file specified.
> 
> Are you using the same certificate template on both Windows and Linux? My guess is that "Publish certificate in Active Directory" is not enabled on the template.

I don't know. In Linux we don't specify any template. I found in certmonger:
-ms-template-spec SPEC
              Include a V2 Certificate Template extension in the signing request.  This datum includes an Object Identifier, a major version number (positive integer)
              and an optional minor version number.  The format is: <oid>:<majorVersion>[:<minorVersion>].

But I have yet to figure out what args to pass here

**Comment by joakim-tjernlund** [comment]
> > > Hi again
> > > Now we have figured out why not wifi TLS work against APs. The cert is fine but an extar step fails:
> > > > Active Directory Certificate Retrieval for Certificate-Based Authentication
> > > 
> > > 
> > > > Cisco ISE supports certificate retrieval for user and machine authentication that uses the EAP-TLS protocol. The user or machine record on Active Directory includes a certificate attribute of the binary data type. This certificate attribute can contain one or more certificates. Cisco ISE identifies this attribute as userCertificate and does not allow you to configure any other name for this attribute. Cisco ISE retrieves this certificate and uses it to perform binary comparison.
> > > 
> > > 
> > > > The certificate authentication profile determines the field where the username is taken from in order to lookup the user in Active Directory to be used for retrieving certificates, for example, Subject Alternative Name (SAN) or Common Name. After Cisco ISE retrieves the certificate, it performs a binary comparison of this certificate with the client certificate. When multiple certificates are received, Cisco ISE compares the certificates to check for one that matches. When a match is found, the user or machine authentication is passed.
> > > 
> > > 
> > > This "userCertificate" is not created for Linux clients and we suspect that cepces does something different
> > > than what Windows does. Does this make any sense to you?
> > 
> > 
> > Nothing I've looked into. Basically, `certmonger` generates a CSR that it feeds to `cepces`. This CSR is then sent verbatim to the CA server. The result contains a PEM encoded certificate that is then fed back to `certmonger` which then stores the certificate in the file specified.
> > Are you using the same certificate template on both Windows and Linux? My guess is that "Publish certificate in Active Directory" is not enabled on the template.
> 
> I don't know. In Linux we don't specify any template. I found in certmonger:
> -ms-template-spec SPEC
> Include a V2 Certificate Template extension in the signing request. This datum includes an Object Identifier, a major version number (positive integer)
> and an optional minor version number. The format is: :[:].
> 
> But I have yet to figure out what args to pass here

Found some OID on the web:1.2.840.113556.1.4.1436 but that only gave me an error:
	ca-error: Denied by Policy Module  0x80094802, The request specifies conflicting certificate templates: Machine/1.2.840.113556.1.4.1436.

**Comment by ufven** [comment]
> Could this be related to Appendix A , enrollmentFlags (0x00000008):
> Instructs the CA to append the issued certificate to the userCertificate attribute, on the user
> object in Active Directory.

`enrollmentFlags` is returned in a CEP response, so this wouldn't be applicable in your scenario.

> Found some OID on the web:1.2.840.113556.1.4.1436 but that only gave me an error:
> ca-error: Denied by Policy Module 0x80094802, The request specifies conflicting certificate templates: Machine/1.2.840.113556.1.4.1436.

Ah, I take it you're using the standard `Computer/Machine` template? It's a very old one and doesn't publish to AD by default. IIRC, you can't change it either (schema version 1). Are you sure that your Windows clients are also enrolling from that template? In that case, it sounds like they shouldn't have that attribute either. Is this something you could verify?

One option would be to duplicated the `Workstation` template (schema version 2) and make modifications to it, alternatively just modify that standard template.

**Comment by joakim-tjernlund** [comment]
> > Could this be related to Appendix A , enrollmentFlags (0x00000008):
> > Instructs the CA to append the issued certificate to the userCertificate attribute, on the user
> > object in Active Directory.
> 
> `enrollmentFlags` is returned in a CEP response, so this wouldn't be applicable in your scenario.
> 
> > Found some OID on the web:1.2.840.113556.1.4.1436 but that only gave me an error:
> > ca-error: Denied by Policy Module 0x80094802, The request specifies conflicting certificate templates: Machine/1.2.840.113556.1.4.1436.
> 
> Ah, I take it you're using the standard `Computer/Machine` template? It's a very old one and doesn't publish to AD by default. IIRC, you can't change it either (schema version 1). Are you sure that your Windows clients are also enrolling from that template? In that case, it sounds like they shouldn't have that attribute either. Is this something you could verify?

I have no idea how the Windows machines are enrolling, I can ask Windows IT to check but I am not sure they know howto, do you have a command handy ?

> 
> One option would be to duplicated the `Workstation` template (schema version 2) and make modifications to it, alternatively just modify that standard template.

I just tried getcert request -c cepces -T Workstation .... and that got me a certificate too but no
userCertificate. What more Templates are there ? Google isn't helping, probably because I don't know what to search for ....

**Comment by joakim-tjernlund** [comment]
From https://winintro.ru/certtmpl.en/html/e6868771-654b-44fd-9853-7cbdd9174f47.htm I found
User template and that seems to do the trick,  gets a cert and it creates an userCertificate attribute for my
computer. Testing whether it works needs to wait until tomorrow though ...

**Comment by ufven** [comment]
> I have no idea how the Windows machines are enrolling, I can ask Windows IT to check but I am not sure they know howto, do you have a command handy ?

I'm no PowerShell wizard, but try if this works (in an administrative PowerShell session): `Get-ChildItem "Cert:\LocalMachine\My" | ForEach-Object { $subject = $_.Subject; $thumbprint = $_.Thumbprint; $_.Extensions | Where-Object { $_.Oid.Value -eq "1.3.6.1.4.1.311.20.2" } | ForEach-Object { [PSCustomObject] @{"Subject" = $subject; "Thumbprint" = $thumbprint; "Template" = $_.Format(0)} } } | Format-Table`

> User template and that seems to do the trick, gets a cert and it creates an userCertificate attribute for my computer.

This is probably due to that the default User certificate template has the option "Publish certificate in Active Directory".

**Comment by joakim-tjernlund** [comment]
> > I have no idea how the Windows machines are enrolling, I can ask Windows IT to check but I am not sure they know howto, do you have a command handy ?
> 
> I'm no PowerShell wizard, but try if this works (in an administrative PowerShell session): `Get-ChildItem "Cert:\LocalMachine\My" | ForEach-Object { $subject = $_.Subject; $thumbprint = $_.Thumbprint; $_.Extensions | Where-Object { $_.Oid.Value -eq "1.3.6.1.4.1.311.20.2" } | ForEach-Object { [PSCustomObject] @{"Subject" = $subject; "Thumbprint" = $thumbprint; "Template" = $_.Format(0)} } } | Format-Table`
> 
Will pass that on to Win IT, thanks.

> > User template and that seems to do the trick, gets a cert and it creates an userCertificate attribute for my computer.
> 
> This is probably due to that the default User certificate template has the option "Publish certificate in Active Directory".

Yes, it does have that. But now I got a bad Alt Name:
      othername: unsupported
so thats no good either :(

**Comment by ufven** [comment]
Any update? Did you manage to figure out what template is used on Windows?

**Comment by joakim-tjernlund** [comment]
Not yet, the guy handling this has been very busy/sick so it is still waiting.
Looking at the standard templates listed at:
 https://winintro.ru/certtmpl.en/html/e6868771-654b-44fd-9853-7cbdd9174f47.htm
there does not  seems to be a fitting template.
 
I suspect Windows use some extra param they pass to the CA server when creating  the crt.

**Comment by joakim-tjernlund** [comment]
Windows uses the Workstation Template bu when I try I an error, policy denied (or similar)
Also, the Workstation template does not have the AD object flag set so it is an mystery how Windows
manages to create Certs and get an AD object.
Feels like Windows has some way of passing extra flags parameters for AD object creation.

Are you sure one cannot add enrollmentFlags (or similar) to CES?

**Comment by ufven** [comment]
> Windows uses the Workstation Template but when I try I get an error, policy denied (or similar)
Also, the Workstation template does not have the AD object flag set so it is an mystery how Windows
manages to create Certs and get an AD object.
Feels like Windows has some way of passing extra flags parameters for AD object creation.

This is a permission error on the server end. Are you sure your account (computer I take it) is allowed to enroll a certificate of that type?

> Are you sure one cannot add enrollmentFlags (or similar) to CES?

I've only seen enrollmentFlags in the the MS-XCEP specification, not in MS-WSTEP (which is the one used for enrolling certificates.) It's also an element in the response, not the request, so I cannot influence those flags in any request that I'm aware of.

**Comment by joakim-tjernlund** [comment]
Any advances/fixes over the summer ? Seems like you forgot to push the PKCS7Converter to
StringConverter fix.

**Comment by ufven** [comment]
I pushed it in 279d11d, and tagged it v0.3.3, so the fix should be there :-) I looked at implementing the PKCS7Converter, but I can't seem to find support for that in the cryptography package I'm using. Haven't done much else, been occupied with a few other projects.

Did you ever get it to enroll a certificate? Did Win IT get back to you on the template configuration? The one you enroll has to populate the userCertificate LDAP attribute from the looks of the error you described earlier. I know the default Machine template doesn't do that, so I guess the Windows clients use some other template.

**Comment by joakim-tjernlund** [comment]
Sorry, I didn't check the logs properly :)

No, it isn't solved yet :(
I do have a theory though, Windows machines are joined with another user and I think this user is connected to AutoEnrollment (search google with "autoenroll windows ad certificate")
Not sure how to combine AutoEnrollment with cepces though since the cert is created when joining the domain. Any ideas about that?

**Comment by joakim-tjernlund** [comment]
BTW, now I why I was confused w.r.t v0.3.3 release, there is only a tag, the fix is not in any branch.

**Comment by ufven** [comment]
Sorry, that commit was only the version bump. Here's the change between 0.3.2 and 0.3.3: https://github.com/ufven/cepces/compare/v0.3.2...v0.3.3

**Comment by ufven** [comment]
> I do have a theory though, Windows machines are joined with another user and I think this user is connected to AutoEnrollment (search google with "autoenroll windows ad certificate")
> Not sure how to combine AutoEnrollment with cepces though since the cert is created when joining the domain. Any ideas about that?

Windows machines usually use their own account (e.g. `COMPUTER$`), which probably have the correct permissions to enroll a certain template. If you could find a Windows computer, gain admin privileges on it, and then run the PowerShell snippet above, you should be able to see what template they're using. If your computer has the same privileges as them, you should be able to configure certmonger to use that same template. The CA should then populate the `userCertificate` attribute for you.

**Comment by joakim-tjernlund** [comment]
Using the Get-ChildItem "Cert:\LocalMachine\My" cmd we only get:

```
PSParentPath: Microsoft.PowerShell.Security\Certificate::LocalMachine\My

 

Thumbprint                                Subject

----------                                -------

C0A306B0D99D7466724486D4A455A0E325DCC584  CN=9b038721-4c9d-4b16-83cc-b86bfe733588

884DFA89DDE4C02109F02E33AB58BC4B8FF3F965  CN=9b038721-4c9d-4b16-83cc-b86bfe733588, DC=285643de-5f5b-4b03-a153-0ae2dc...

3619AE64C68C47C1700E405EF3970A91CFF2399D
```
If I filter that through the remaining pipe there is no output

**Comment by joakim-tjernlund** [comment]
I think this done since long
